baseURL = "https://lunlightup.github.io/"
languageCode = "en-us"
title = "Lubov Kozlova"
theme = "minimal"
disqusShortname = "https-lunlightup-github-io"
googleAnalytics = "G-65MWQD5LL1"

[params]
    author = "Lubov Kozlova"
    description = "personal blog"
    githubUsername = "#"
    accent = "orange"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]
    favicon = 'favicon.ico'

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 3

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "mailto:lunlightup@gmail.com"
    name = "fas fa-envelope"
    weight = 1

[[menu.icon]]
    url = "https://github.com/lunlightup/"
    name = "fab fa-github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/lunlight/"
    name = "fab fa-twitter"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/lubov-kozlova-a0705182/"
    name = "fab fa-linkedin"
    weight = 4

[[menu.icon]]
    url = "https://stackoverflow.com/users/12517863/lubov-vashpanova"
    name = "fab fa-stack-overflow"
    weight = 5
